In [3]:
import tiktoken

def get_num_tokens(text: str, model_name: str = "gpt-4.1") -> int:
    encoding = tiktoken.encoding_for_model(model_name)
    return len(encoding.encode(text))

# MedCalc

In [2]:
from datasets import load_dataset

medcalc_df = load_dataset("ncbi/MedCalc-Bench-v1.1", split="test").to_pandas()
medcalc_df = medcalc_df[['Row Number','Patient Note', 'Question']]
medcalc_df['question'] = medcalc_df['Question'].copy()#map(lambda x: x.split('?')[0].strip())
medcalc_df.head(2)

/Users/vuong/Downloads/research/repos/numeric-reasoning/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,Row Number,Patient Note,Question,question
0,1,An 87-year-old man was admitted to our hospita...,What is the patient's Creatinine Clearance usi...,What is the patient's Creatinine Clearance usi...
1,2,An 83-year-old man with a past medical history...,What is the patient's Creatinine Clearance usi...,What is the patient's Creatinine Clearance usi...

## Mean Ctx Len

In [3]:
round(medcalc_df['Patient Note'].map(lambda x: get_num_tokens(x, "gpt-4.1")).mean(),0)

np.float64(613.0)

## Mean Quesion Len

In [4]:
round(medcalc_df['question'].map(lambda x: get_num_tokens(x, "gpt-4.1")).mean(),0)

np.float64(41.0)

# Ours

In [2]:
import os
import pandas as pd

def get_full_data(dir: str):
    full_df = pd.DataFrame()
    for task in ["comparison", "summary", "retrieval", "calculation"]:
        for subtask in os.listdir(os.path.join(dir, task)):
            df = pd.read_csv(os.path.join(dir, task, subtask))
            full_df = pd.concat([full_df, df])
    full_df['context'] = full_df['question'].map(lambda x: "\n".join(x.split('\n\n')[:-1]).strip())
    full_df['question'] = full_df['question'].map(lambda x: x.split('\n\n')[-1].strip())#.split('?')[0].strip())
    return full_df

## Question length

In [8]:
data_dir = "/Users/vuong/Downloads/research/repos/numeric-reasoning/data/med_numeracy/natural"
df = get_full_data(data_dir)
df.head(2)

,question,answer,open_ended_answer,dataset_source,context
0,What is the record datetime when temperature i...,2133-05-21 05:15:00,2133-05-21 05:15:00,comparison_superlative_highest,"At 2133-05-20 23:58:00, A 77-year-old left han..."
1,What is the record datetime when temperature i...,2133-05-21 11:36:00,2133-05-21 11:36:00,comparison_superlative_lowest,"At 2133-05-20 23:58:00, A 77-year-old left han..."

In [9]:
round(df['question'].map(lambda x: get_num_tokens(x, "gpt-4.1")).mean(), 0)

np.float64(23.0)

## Structured

In [27]:
data_dir = "/Users/vuong/Downloads/research/repos/numeric-reasoning/data/med_numeracy/structured"
df = get_full_data(data_dir)
round(df['context'].map(lambda x: get_num_tokens(x, "gpt-4.1")).mean(), 0)

np.float64(745.0)

In [28]:
df['context'].iloc[0]

'{\n    chart_time: 2133-05-20 23:58:00,\n    age: 77,\n    gender: male,\n    pain: 10,\n    temperature: 36.9,\n    heart_rate: 77,\n    resp_rate: 14,\n    o2_sat: 98,\n    bp: 171/66\n},\n{\n    chart_time: 2133-05-21 05:15:00,\n    age: 77,\n    gender: male,\n    pain: NAD,\n    temperature: 37.0,\n    heart_rate: 80,\n    resp_rate: 16,\n    o2_sat: 99,\n    bp: 100/57\n},\n{\n    chart_time: 2133-05-21 09:42:00,\n    age: 77,\n    gender: male,\n    pain: uta,\n    temperature: 36.7,\n    heart_rate: 73,\n    resp_rate: 25,\n    o2_sat: 100,\n    bp: 97/52\n},\n{\n    chart_time: 2133-05-21 11:36:00,\n    age: 77,\n    gender: male,\n    pain: uta,\n    temperature: 36.6,\n    heart_rate: 65,\n    resp_rate: 30,\n    o2_sat: 100,\n    bp: 109/58\n}'

## Templated

In [24]:
data_dir = "/Users/vuong/Downloads/research/repos/numeric-reasoning/data/med_numeracy/templated"
df = get_full_data(data_dir)
round(df['context'].map(lambda x: get_num_tokens(x, "gpt-4.1")).mean(), 0)

np.float64(551.0)

In [25]:
df['context'].iloc[0]

'At 2133-05-20 23:58:00, the 77-year-old male reports pain level is 10. His vital sign at the time is temperature 36.9°C, heart rate 77 bpm, respiratory rate 14 bpm, O2 saturation 98%, blood pressure 171/66 mmHg. At 2133-05-21 05:15:00, the 77-year-old male reports pain level is NAD. His vital sign at the time is temperature 37.0°C, heart rate 80 bpm, respiratory rate 16 bpm, O2 saturation 99%, blood pressure 100/57 mmHg. At 2133-05-21 09:42:00, the 77-year-old male reports pain level is uta. His vital sign at the time is temperature 36.7°C, heart rate 73 bpm, respiratory rate 25 bpm, O2 saturation 100%, blood pressure 97/52 mmHg. At 2133-05-21 11:36:00, the 77-year-old male reports pain level is uta. His vital sign at the time is temperature 36.6°C, heart rate 65 bpm, respiratory rate 30 bpm, O2 saturation 100%, blood pressure 109/58 mmHg.'

## Templated padding

In [10]:
data_dir = "/Users/vuong/Downloads/research/repos/numeric-reasoning/data/med_numeracy/padding_templated"
df = get_full_data(data_dir)
round(df['context'].map(lambda x: get_num_tokens(x, "gpt-4.1")).mean(), 0)

np.float64(1475.0)

## Variant

In [29]:
data_dir = "/Users/vuong/Downloads/research/repos/numeric-reasoning/data/med_numeracy/natural"
df = get_full_data(data_dir)
round(df['context'].map(lambda x: get_num_tokens(x, "gpt-4.1")).mean(), 0)

np.float64(1480.0)

In [30]:
df['context'].iloc[0]

"At 2133-05-20 23:58:00, A 77-year-old left hand-dominant female first presented to the emergency department (ED) as a transfer from an outlying facility (OLF) secondary to an African grey parrot (Psittacus erithacus) bite. The patient was cleaning her pet parrot’s cage at 09:30 hours when she sustained a bite to the dorsum of the right hand. She experienced immediate pain but upon examination, there were no breaks in the skin. The patient then washed the area with antibacterial soap and applied an ice pack. Throughout the day, the pain, swelling, and bruising continued to increase and eventually spread to her dorsal wrist. The pain became unbearable and so she sought care at her local ED. The OLF performed labs and a hand X-ray. She was given one dose of intravenous (IV) ceftriaxone 1 g and transferred to our ED for evaluation by hand surgery. The patient arrived at our facility and was evaluated at 1931. The patient was complaining of increased pain, numbness, and coolness all over the dorsum of the hand. She also stated the swelling had progressed to the distal third of the dorsal forearm from the time of evaluation at the OLF until the time of arrival. She denied systemic symptoms.\nThe patient’s initial vital signs were temperature 36.9 °C, blood pressure 171/66, heart rate 77 beats per minute, respiratory rate 14 breaths per minute, and oxygen saturation of 98% on room air. On physical exam, the right hand had ecchymosis and soft tissue edema to all five digits as well as the dorsum of the hand with an extension to the distal third of the dorsal forearm. At the proximal third of the dorsal forearm, there was soft tissue swelling, induration, erythema, and fluctuance. No crepitus was noted. There was no swelling beyond the area of erythema. The right hand was cold when compared to the left hand. The digits were held in slight flexion. There was a decreased range of motion with extension and flexion in all five digits as well as wrist extension. There was tenderness to palpation to all five digits, dorsum of the hand, and the dorsal forearm. Radial and brachial pulses were two plus and equal bilaterally. Median, radial and ulnar nerve sensation were intact.\nThe patient had a basic metabolic panel and complete blood count at OLF, which were unremarkable. Her hand X-ray from OLF was interpreted as having soft tissue swelling without evidence of fracture. Given the clinical suspicion of ACS, the hand surgeon was contacted and requested a computed tomography (CT) scan of the extremity with intravenous contrast (Figures -). The patient was evaluated by the hand surgeon at 20:15 hours and taken immediately to the operating room. She was given a tetanus shot and azithromycin 500 mg IV to empirically cover for C. psittaci given the history of a bird bite. The CT scan was interpreted as having soft tissue swelling of the dorsal hand without fluid collection or bony abnormality (arrows denote swelling).\nIn the operative suite, the patient underwent a right-hand fasciotomy. The first incision was made over the third metacarpal into the deep fascia of the dorsum of the hand. A large non-purulent fluid collection was encountered and cultures were obtained. Next, the fascia of the right thenar musculature was released. Finally, the fascia of the right hypothenar musculature was released. After the fasciotomy, the surgeon drained an abscess involving the forearm and iodoform packing was placed. No necrotic tissue was noted. Lastly, the median nerve was released at the carpal tunnel and the ulnar nerve was released at Guyon’s canal to prevent further compression of the nerves. The patient was sent to recovery without complications.\nThe next day she was evaluated by an infectious disease specialist. They recommended changing her antibiotics to amoxicillin/clavulanate and doxycycline. The patient's wounds continued to improve over the course of her hospitalization. Forty-eight hours after her first procedure, she was taken back to the operative suite for secondary closure of the wounds of the dorsum of the hand and the forearm. All cultures, including aerobic, anaerobic, and fungal, were negative. The patient was discharged home on day three of her admission to complete a 14-day course of antibiotics. She was also given outpatient physical therapy to work on wrist range of motion. At her two-week follow-up, the patient was found to have improved sensation, strength, and range of motion. Her wounds were healing appropriately without any further swelling or drainage.. At 2133-05-21 05:15:00, heart rate of 80, peripheral capillary oxygen saturation (SpO2) of 99%, temperature of 37.0°C, blood pressure of 100/57 mmHg, and respiratory rate of 16 breaths per minute. At 2133-05-21 09:42:00, temperature, 36.7°C; heart rate, 73 beats/min with regular rhythm; respiratory rate, 25 breaths/min; blood pressure, 97/52 mmHg; and peripheral oxygen saturation, 100% in room air. At 2133-05-21 11:36:00, Pulse-65 beats/min, regular, BP-109/58 mmHg, RR-30/min, SpO2-100% on room air and Temperature 36.6 degree C"